const es = {
    '/dashboard': 'dashboard',
    '/custom-layout-change': 'dashboard',
    '/grouped-email': 'review/email',
    '/emails/files': 'review/reported-attachment',
    '/stats/report-email': 'review/overall-stats',
    '/company-policy': 'company-policies',
    '/yara-rules': 'yara-rules',
    '/image-analysis': 'image-analysis',
    '/rules': 'rules',
    '/eventlogs': 'eventlogs',
    '/admin/auth/user': 'settings/users',
    '/saml-setting': 'saml-setting',
    '/syslog-settings': 'syslog-setting',
    '/get-cip-sitelinks': 'cip-setting',
    '/licenses': 'licenses',
    '/free-email-hosts': 'data-feed/free-email-hosts',
    '/free-web-mail-hosts': 'data-feed/free-web-hosts',
    '/url-shortners': 'data-feed/url-shortener',
    '/spear-phishing-url': 'data-feed/spear-phish-urls',
    '/white-listed-domains': 'data-feed/white-listed-domains',
    '/black-listed-domains': 'data-feed/black-listed-domains',
    '/black-listed-ip': 'data-feed/black-listed-ips',
    '/keyword': 'data-feed/keywords',
    '/hash': 'data-feed/hash',
    '/company-policy/user-lookup': 'company-policies/view-user/',
    '/auth/me': 'personal-settings'
};
const dt = {
    '/dashboard': 'dashboard',
    '/widgets': 'dashboard',
    '/services': 'control-center',
    '/get-nodes-services': 'control-center',
    '/get-commands-status': 'control-center',
    '/bread-crumbs': 'breadcrumbs',
    '/nodes-list': 'breadcrumbs',
    '/node-services': 'breadcrumbs',
    '/get-service-node-auth-data': 'breadcrumbs',
    '/group-credentials': 'group-credentials',
    '/honyepot-list': 'decoy',
    '/get-directory-data': 'decoy',
    '/get-license-controllered-features': 'incidents',
    '/report-incidents': 'incidents',
    '/incident-filter-options': 'incidents',
    '/incident-files': 'incident-files',
    '/cases': 'cases',
    '/cases-breadcrumb': 'cases',
    '/automatic-cases-creation': 'automatic-cases-creation',
    '/users': 'users',
    '/modules': 'users',
    '/list': 'users',
    '/role': 'users',
    '/groups': 'users',
    '/roles/list': 'users',
    '/role-by-id': 'users',
    '/role-setting': 'users',
    '/system-setting': '/system-settings',
    '/version-data': 'auto-update',
    '/emailSettings': 'emails',
    '/saml-setting-list': 'saml-settings',
    '/smsSettings': 'smsSetting',
    '/sysLogSettings': 'syslogs',
    '/av-scan-settings': 'av-scan-settings',
    '/virus-total-settings': 'virus-total-settings',
    '/backups': 'database-setting',
    '/backup': 'database-setting',
    '/packages': 'update-packages',
    '/platforms': 'update-packages',
    '/user/detail': 'user-profile',
    '/user/key': 'user-profile'
};
const eps = {
    '/widgets': 'dashboard',
    '/module-data-for-dashboard': 'dashboard',
    '/dashboard': 'dashboard',
    '/get-unread-reports-count': 'alert',
    '/get-process-list': 'alert',
    '/all-tags': 'alert',
    '/cases': 'alert',
    '/phoenix-process-list': 'alert',
    '/misc-attacks': 'alert',
    '/get-process': 'view-process',
    '/get-process-classifications': 'view-process',
    '/save-classification': 'view-process',
    '/get-activities-list': 'view-process',
    '/all-black-lists': 'process-policies',
    '/get-nodes': 'process-policies',
    '/black-list': 'process-policies',
    '/whitelist-mode-policies': 'whitelist-mode-policies',
    '/whitelist-process-groups': 'whitelist-mode-policies',
    '/work-station-groups': 'whitelist-mode-policies',
    '/pending-whitelists': 'pending-whitelist',
    '/get-pending-whitelist-activities': 'view-pending-whitelist',
    '/get-pending-whitelist': 'view-pending-whitelist',
    '/most-hash-report': 'view-pending-whitelist',
    '/usb-classes': 'usb-policy',
    '/get-usb-policy-types': 'usb-policy',
    '/get-usb-policy-targets': 'usb-policy',
    '/network-rule': 'network-rule',
    '/work-station-groups': 'network-rules',
    '/phoenix-policies': 'phoenix-policies',
    '/web-app-policy': 'web-app-policies',
    '/web-apps': 'web-app-policies',
    '/misc-attacks': 'web-app-policies',
    '/update-script-logging-status': 'script-logging-policy',
    '/get-fullNetwork-mode': 'endpoint',
    '/update-workstation-mode': 'endpoint',
    '/confinement': 'network-confinement',
    '/confinement-whitelist': 'network-confinement',
    '/get-process-list-by-hash': 'process-status-report',
    '/get-process-filter': 'process-status-report',
    '/get-commands-status': 'commands-results',
    '/get-command-result': 'commands-results',
    '/executable-file-list': 'launch-app-module',
    '/get-launch-list': 'launch-app-module',
    '/executable-file-list': 'launch-app-module',
    '/samba-shares': 'edr-console-tabs',
    '/disk-encryptions': 'disk-encryptions',
    '/get-startup-lists': 'startup-lists',
    '/installed-apps': 'installed-applications',
    '/installed-apps-details': 'view-application',
    '/installed-app': 'view-application',
    '/system-policies': 'system-settings',
    '/system-setting': 'system-settings',
    '/samba-shares': 'samba-shares',
    '/get-cip': 'cip-settings',
    '/operating-systems': 'system-settings',
    '/packages': 'system-settings',
    '/download-updated-package': 'update-management',
    '/users': 'user-management',
    '/user': 'user-management',
    '/user-role-list': 'user-managment',
    '/operating-systems': 'system-settings',
    '/get-workStation-groups-for-updates': 'update-workstations',
    '/get-update-management-nodes': 'update-workstations',
    '/system-policy': 'system-settings',
    '/events': 'event-viewer',
    '/event-filters': 'event-viewer',
    '/get-modules-for-user': 'user-managment',
    '/multi-admin-policy-list': 'multi-admin-approval',
    '/modules': 'multi-admin-approval',
    '/admin-list': 'multi-admin-approval',
    '/smsSettings': 'sms-setting',
    '/virus-total-settings': 'virus-total-setting',
    '/saml-setting-list': 'saml-setting',
    '/user-details': 'user-managment',
    '/sysLogSettings': 'syslogs',
    '/backups': 'database-setting',
    'notification-settings-modules': 'notifications-setting',
    '/slackSettings': 'slack-setting',
    '/slack-integration-link': 'slack-setting',
    '/download': 'user',
    '/notification-settings': 'notification-setting',
    '/qr-code': 'user'
};
const acme = {
    '/settings': 'settings',
    '/dashboard': 'dashboard',
    '/vulnerability': 'vulnerability-templates',
    '/permission': 'user',
    '/projects': 'projects',
    '/toggle-user-data': 'user',
    '/user': 'user',
    '/devices': 'user',
    '/project': 'projects',
    '/pentest-profile': 'find-work',
    '/projectjob': 'find-work',
    '/project-bid-profile': 'find-work',
    '/executive-summary-template': 'executive-summary-templates',
    '/company': 'cip-settings',
    '/pentest-profile': 'pentest-profile',
    '/syslog-settings': 'syslog-settings'
};

const updatePortal = {
    '/software': 'softwares',
    '/client-user': 'user-managment',
    '/user': 'user-managment',
    '/personal-setting': 'personal-setting',
    '/client': 'user-managment',
    '/devices': 'account-setting',
    '/generate-2fa-token': 'account-setting',
    '/login-sessions': 'active-sessions'
};

module.exports = {
    es,
    dt,
    eps,
    acme,
    updatePortal
};
