
GET https://localhost/myApi/get

###
POST https://localhost/myApi/create/1?name=rohail
Content-Type: application/json

{
    "targetUrl":"https://google.com",
    "body":"{'email':'rohailbutt@gmail.com','password':'11979944'}"
}

###
GET http://localhost:3000/myApi/create/2?name=nabeel

###

GET http://localhost:3000/app

###


