
GET https://localhost/myApi/get

###
POST http://localhost:3000/myApi/create/1?name=rohail
Content-Type: application/json

{
    "targetUrl":"https://google.com",
    "body":"{'email':'rohailbutt@gmail.com','password':'11979944'}"
}

###
GET http://localhost:3000/myApi/create/2?name=nabeel

###

GET http://localhost:3000/app

###

GET http://localhost:3000/proxy/1

###
POST https://es.revbits.com/api/v2/auth/login
Content-Type: application/json

{
    "email": "rohail.butt+1@invozone.com",
    "password": "b7d4e49a3fd7f9b1eec6088188baf30a76c2a20ec102f4c82d2f5abe3fa88c544497d05c31abd1cceae1ac8f44916b225ef04ed911f0fea0c903ed71cd018e30!"
}
